// Generated by CoffeeScript 1.12.6
(function() {
  var PORT, app, express;

  express = require('express');

  app = express();

  PORT = process.env.PORT || 3000;

  app.use(function(req, res, next) {
    var localhost;
    localhost = req.headers['host'].slice(0, 9);
    if (req.headers['x-forwarded-proto'] === 'http' || req.headers['host'].slice(0, 9) === localhost) {
      return next();
    } else {
      return res.redirect('http//' + req.hostname + req.url);
    }
  });

  app.use(express["static"]('public'));

  app.listen(PORT, function() {
    return console.log('Express server is up serving on port ' + PORT);
  });

}).call(this);
